version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: kachi-dynamodb
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes:
      - ./kachi:/data
    ports:
      - "8000:8000"
    expose:
      - "8000"
      