version: "3.6"
services:
  black-box-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: black-box-zookeeper
    container_name: black-box-zookeeper
    ports:
      - "2181:2181"
    networks:
      - k36t_net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./black-box-zookeeper/data:/data
      - ./black-box-zookeeper/datalog:/datalog

  black-box-kafka:
    image: confluentinc/cp-kafka:latest
    hostname: black-box-kafka
    container_name: black-box-kafka
    depends_on:
      - black-box-zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    networks:
      - k36t_net
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "black-box-zookeeper:2181"
      KAFKA_LISTENERS: LISTENER1://black-box-kafka:29092,LISTENER2://black-box-kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER1://black-box-kafka:29092,LISTENER2://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER1:PLAINTEXT,LISTENER2:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - ./black-box-kafka/data:/var/lib/black-box-kafka/data

  black-box-schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: black-box-schema-registry
    container_name: black-box-schema-registry
    depends_on:
      - black-box-kafka
    ports:
      - "8081:8081"
    networks:
      - k36t_net
    environment:
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_HOST_NAME: black-box-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: black-box-zookeeper:2181
      
  black-box-kafka-connect:
    image: confluentinc/cp-kafka-connect:latest
    hostname: black-box-kafka-connect
    container_name: black-box-kafka-connect
    depends_on:
      - black-box-kafka
      - black-box-zookeeper
    ports:
      - "8083:8083"
    networks:
      - k36t_net
    volumes:
      - /tmp/omniscient/jars:/etc/kafka-connect/jars
    environment:
      CONNECT_BOOTSTRAP_SERVERS: black-box-kafka:9092”
      CONNECT_REST_ADVERTISED_HOST_NAME: black-box-kafka-connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: “org.apache.kafka.connect.json.JsonConverter”
      CONNECT_INTERNAL_VALUE_CONVERTER: “org.apache.kafka.connect.json.JsonConverter”
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: “1”
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: “1”
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: “1”
      CONNECT_PLUGIN_PATH: ‘/usr/share/java,/etc/kafka-connect/jars’
      CONNECT_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1

  black-box-rest-proxy:
    image: confluentinc/cp-kafka-rest:latest
    hostname: black-box-rest-proxy
    container_name: black-box-rest-proxy
    depends_on:
      - black-box-kafka
      - black-box-zookeeper
    networks:
      - k36t_net
    environment:
      KAFKA_REST_HOST_NAME: black-box-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: "black-box-kafka:29092"
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: "http://black-box-schema-registry:8081"

  

networks:
  k36t_net:
    driver: bridge

volumes:
  rs1:
